apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  labels:
    app: {{ .Values.appName }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
type: Opaque
data:
  {{- $encodedPAT := b64enc .Values.githubPat }}
  {{ .Values.secretKey }}: {{ $encodedPAT }}
