apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: {{ .Values.appName }}
          image: {{ .Values.runnerImage }}:{{ .Values.runnerTag }}
          imagePullPolicy: Always

          securityContext:
            privileged: {{ .Values.privileged }}

          resources:
            limits:
              memory: {{ .Values.memoryLimit }}
              cpu: {{ .Values.cpuLimit }}

          env:
            - name: GITHUB_OWNER
              value: {{ required ".Values.githubOwner must be set." .Values.githubOwner }}
            - name: GITHUB_REPOSITORY
              value: {{ .Values.githubRepository }}
            - name: RUNNER_LABELS
              value: {{ .Values.runnerLabels }}
            - name: GITHUB_PAT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: {{ .Values.secretKey }}
            # Any injected env values from values.yaml will go below
              {{- range .Values.runnerEnv }}
            - name: {{ .name }}
              value: {{ .value }}
        {{- end }}
