appName: runner
image: quay.io/redhat-github-actions/redhat-actions-runner
tag: latest
replicas: 1

githubOwner: ""
githubRepository: ""

# Pass labels comma-delimited. If setting through the helm command line, commas must be escaped.
# --set runnerLabels="label1\,label2" results in the labels "label1" and "label2".
runnerLabels: ""

memoryLimit: '1Gi'
cpuLimit: '750m'

privileged: false

runnerEnv:
    # You can inject environment variables here:
    # - name: ENV_VAR
    #   value: env_value
    # or, through the command line:
    # --set runnerEnv[0].name="ENV_VAR" --set runnerEnv[0].value="env_value"
